- name: Install Nginx
  dnf: name=nginx state=latest

- name: Create nginx site directories
  file: path={{ item.path }} owner=root group=root state=directory
  with_items:
    - { path: '/etc/nginx/sites-available' }
    - { path: '/etc/nginx/sites-enabled' }

- name: Configure nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root
  notify: restart nginx

- name: Enable nginx
  service: name=nginx enabled=yes state=started

- name: Allow http/https through firewall
  firewalld: port={{ item }} state=enabled permanent=yes immediate=yes
  with_items:
    - 80/tcp
    - 443/tcp

