- name: Install security-related packages
  dnf: name={{ item }} state=latest
  with_items:
    - fail2ban
    - lynis
    - rkhunter

- name: Copy fail2ban configuration into place
  template: src=etc_fail2ban_jail.local.j2 dest=/etc/fail2ban/jail.local
  notify: restart fail2ban

- name: Copy fail2ban ownCloud config into place
  template:
    src: f2b_owncloud.conf.j2
    dest: /etc/fail2ban/filter.d/owncloud.conf
  notify: restart fail2ban

- name: Copy fail2ban dovecot configuration into place
  template: 
    src: f2b_dovecot-imaps.conf.j2
    dest: /etc/fail2ban/filter.d/dovecot-imaps.conf
  notify: restart fail2ban

- name: Enable Fail2Ban
  service: name=fail2ban enabled=yes state=started

- name: Update sshd config for PFS and more secure defaults
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config
  notify: restart ssh

