---
# Installs and configures ufw, which in turn uses iptables for firewall management

# ufw includes sensible icmp defaults
- name: Install ufw
  apt: pkg=ufw state=present
  tags:
    - dependencies

- name: Deny everything
  ufw: policy=deny

#- name: Set firewall rule for DNS
#  ufw: rule=allow port=domain


- name: Set firewall rules for web traffic and SSH
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - 14141 

- name: Enable UFW
  ufw: state=enabled

- name: Check config of ufw
  command: cat /etc/ufw/ufw.conf
  register: ufw_config
  changed_when: False  # never report as "changed"

